spring:
  profiles:
    active: dev
  application:
    name: BankLedger
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankledger}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Let Flyway handle schema changes
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankledger}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.kushagragupta.bankledger: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    com.kushagragupta.bankledger: INFO
    org.springframework.web: WARN

app:
  jwt:
    # This is a sample 256-bit base64-encoded secret key for demonstration purposes
    secret: ${JWT_SECRET:8f434346648f6ea49f43a0595cc092b604e0e687b32876878e1b32d2e1c9e8e5}
    expiration-ms: 86400000 # 24 hours
